---
pool: 'Linux'
trigger:
 - master
stages:
 - stage: 'build'
   jobs:
    - job: 'build'
      steps:
       - task: UsePythonVersion@0
         inputs:
          versionSpec: '3.11'
         displayName: 'Version'
       - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          displayName: 'Install dependencies'
       - script: |
          pip install pytest pytest-azurepipelines
          pytest
          displayName: 'pytest'  
