---
pool:
  vmImage: 'ubuntu-22.04'
trigger:
  - master
stages:
  - stage: "Build"
    jobs:
      - job: "Build_JOB"
        steps:
          - task: "PythonScript@0"
            inputs:
              scriptSource: 'filePath'
              scriptPath: 'hello_app/webapp.py'
            displayName: "Building project"